### ISSUE TITLE
Auto Updated Field Key Duplicates

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#1045]
When you change a field label to exactly the same text as another, it will change the key to match. This is a duplicate, but no error message is displayed.

**Comment by jameslaws** [comment]
Shouldn't this just append a number instead of creating a duplicate? I'm not sure if the user is not explicitly setting a field key that there should ever be a conflict from a user experience point of view. 

Getting a field key error when I'm not messing with field keys feels like it might be a broken experience. I wonder if there is a way to take a "just works" approach if the user isn't manually messing with field keys.

**Comment by kstover** [comment]
Correct

**Comment by jameslaws** [comment]
Cool. Just wanted to make sure we were on the same page. Wasn't completely clear by the description.
