### ISSUE TITLE
Separate html5 required attribute for text fields

### ISSUE THREAD

**Issue by devrahul** [wpninjas/ninja-forms#1114]
Hi is it possible to create a new Separate html5 "required" attribute for input text fields etc for email fields , we want to add html5 "required" attribute.

Please let us know

**Comment by JoeHana** [comment]
Maybe a little late but with that trick you can already set the required attribute within Ninjaforms. Simply add the following to the Custom CSS Classes Field:

`" required tag="`

Since this field obviously doesn't get properly validated, this trick works fine. It basically directly closes the class tag, adds the required tag and the tag at the end is just a pseudo tag to make it work. Try it out and check the source code.

**Comment by kstover** [comment]
We're going to be adding custom attributes in the future, so this would definitely be possible at that point. The work around above isn't guaranteed to work.
