### ISSUE TITLE
Compress Front-End JS

### ISSUE THREAD

**Issue by iamntz** [wpninjas/ninja-forms#1417]
Hey guys. I just noticed couple of things that are not really nice:
1. All loaded JS is around 900+ Kb. For some reasons, compression don't affect the size visibly (1-2kb tops), but i think this is due to my server config. Even so, I doubt this will go lower than 2-300kb, which is still high for a form.
2. The form is generated with JS. This is wrong on so many levels, but considering the 900kb of the JS, this is even worse... Probably it's not a better idea to punish the visitors?

The first issue, however, is solvable...ish. There are few scripts that could be loaded only if needed:
- math (400+kb)
- moment-with-locales (160+kb)
- bootstrap (?!?!?!) 36kb
- codemirror - 100kb
- summernote - 80+kb

And so on. These are simply not needed on a simple contact form.

Hopefully this will change by the time the v3 will finally launch.

**Comment by jameslaws** [comment]
Thanks for all the attention and care you have been placing on the 3.0 code recently. We really appreciate the exta eyes, contributions, and even the holding us accountable. 

To point #1. We still haven't employed our full compression on these just yet. Also, we will be loading things selectively when we get to that point. Only needed js loaded when a form is dependent on it.

To you #2 point. I think both sides of this could be debated. In fact, they have been internally quite a bit. In the end this is where we landed. I'm sure this is a tension we will constantly debate and explore how best to handle as we move forward.

**Comment by iamntz** [comment]
Thanks for your response 

> I think both sides of this could be debated. In fact, they have been internally quite a bit. In the end this is where we landed.

There is any reasoning on this? I'm asking because the result is a fairly simple structure. There is no complex logic to justify a MV* framework.

If the main reason is to reuse templates, then a good alternative would be to use either Handlebars or Mustache. Both of them have JS and PHP versions and for each language templates are fully reusable.

**Comment by kstover** [comment]
Thanks for the I put! As James said, we haven't yet made any optimisation passes at front-end form display. At the moment, it represents something closer to our MVP Dev version. We have plans to move to that area next as we get closer to releasing 3.0 officially. This will become significantly better. 

Like James said, we debated using backbone to build the form with JS internally for a while. In the end, we decided that going with an MV* framework made a lot of sense for us. It's true that for a simple contact form, this might be overkill, but many of our users, especially those that use add-ons, have much more than simple contact forms. Calculations, Input Validation, which is a part of core, the Conditional Logic and Multi-Part Forms add-ons, amongst many others, can significantly change the front-end on the fly.  Rather than relying on Dom manipulation, we decided to approach the form as more of an app than a form. Again, I completely acknowledge that it can be more than a simple contact form needs, but so is our actions system, add-ons, etc. 

Hopefully that helps explain a bit of our reasoning. Thanks again for the comments!

We'll be making the front-end optimisation pass soon.

**Comment by kstover** [comment]
Math.js can also be customised; we don't need all of the functionality of the library. This is something we'll add into our build process for production as well. @kjohnson is working on only loading JS files if the form fields require it. That will help quite a bit. We're also going to be discussing how we load the JSON data and JS files for forms on the front-end.

**Comment by akerd** [comment]
Thank you for the effort, it would be nice have to possibilities to reduce a little bit the size of front-end-deps.js javascript file in case where, for example, mathematical routines or calculations are not needed.

**Comment by kstover** [comment]
We're currently looking at removing the math.js library and lowering the size of the front-end footprint.

**Comment by iamntz** [comment]
No rush here.

(**one** year later...) 💃

**Comment by buzucan** [comment]
2 years later!

**Comment by grettaface** [comment]
Any movement on this?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
