### ISSUE TITLE
Idea: simplify CSS selectors

### ISSUE THREAD

**Issue by iamntz** [wpninjas/ninja-forms#1442]
Probably it's a better idea to add a specific class to the each element, then add style on that class. I mean instead of this:

```
.field-wrap > div input, .field-wrap textarea, .field-wrap select, .field-wrap .pikaday__container, .field-wrap .pikaday__display, .field-wrap .listselect-wrap > div
```

We could have `.field-input` or `.field-component` or something like this (with the class applied dirrectly to the form element).

Reasoning: simpler to override various styling, less specificity and probably in some extreme situation (like HUGE forms) improved render performance.

**Comment by jameslaws** [comment]
We can have a discussion around that, but I've already made them as non specific as possible, but still put conventions I'm to handle overriding bad theme practices and be able to offer opinionated styles when requested. 

For discussion I think a better approach would be to pick a specific field type and a rule for that instance and discuss how it could be simplified.

**Comment by iamntz** [comment]
I'm talking about CSS specificity; for example, here is very high: `.field-wrap .listselect-wrap > div`.

Instead, you could add a class only to that last div. Preferably very generic, like i suggested in the first post.

Additionally, you could inspire from BEM, and having something like `nf__field-component` (so you have some kind of namespacing).

**Comment by jameslaws** [comment]
The problem is those are of opinionated styles where some sales are applied to the div because dropdown are not able to have most styles applied to it and some have to be applied to the select itself. Therefor we have to target to the wrap of the field instead so I can target the sub items of that wrap. You also add more programatic overhead because not you have to create all kinds of different rules to loop through to decide which classes are applied to which elements within a fields markup.
