### ISSUE TITLE
Using font awesome icon inside button label throws out display

### ISSUE THREAD

**Issue by leecollings** [wpninjas/ninja-forms#1460]
I'd like to have an icon appear on the submit button on my form, so I enter the following into the Label field of the button.

`<span class="fa fa-thumbs-up"></span> Sign me up!`

However, this throws out the display on the frontend, and prints `<span class=` on the button, with 'Sign me up!" rel="7" >' underneath the button on a new line.

I tried to solve by replacing the double quotes with single quotes in the label field, but this produced `<span class='fa fa-thumbs-up'></span> Sign me up!` to appear on the button... exactly as it is typed.

![ninjaforms_fontawesome_double-quotes](https://cloud.githubusercontent.com/assets/6681733/16299796/01841d08-3934-11e6-802f-dbfd2834c1f7.png)
![ninjaforms_fontawesome_single-quotes](https://cloud.githubusercontent.com/assets/6681733/16299797/01880792-3934-11e6-9531-6ad33c4666a4.png)

**Comment by leecollings** [comment]
Any news on how to display HTML inside the buttons?

**Comment by kjohnson** [comment]
@leecollings the issue here is that the `submit` field template is an `input type=submit`, as opposed to a `button type=submit`. The HTML in the label is being output inside of the `value` attribute of the input's template.

You can override the `submit` field template with your own to allow for this: http://developer.ninjaforms.com/codex/custom-field-templates/
