### ISSUE TITLE
Migration/Update option shows when it shouldn't

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#1474]
On mastermind.fm, where I have Layout & Styles 1.2.7, MailChimp 3.0, and Conditional Logic 1.4.0, I got notified that our form was jacked up. When I logged in I discovered that my install of Ninja Forms was auto migrated to v3.0 with Layout & Styles and Conditional Logic deactivated.

I've since rolled back and reactivated the two add-ons, but I'm still seeing the "Upgrade to Ninja Forms THREE" admin notice prompt.

This is a big deal that will cause issues for users and need to be fixed immediately.

**Comment by kstover** [comment]
Turns out, this is an issue with our stored add-on json feed. It had Conditional Logic listed as `ninja-forms-conditional-logic` instead of `ninja-forms-conditionals`. The latter is an older naming convention, and we have yet to fully switch over to `ninja-forms-conditional-logic`, so the older convention must be maintained for the time being. Modifying the stored add-on json file so that it is `ninja-forms-conditionals` solves the issue. When we release version 2.9.51, this should take care of the issue.

**Comment by kstover** [comment]
Fixed in eca2f2b7f014fb6c25d5f8b5e467a3eabd616deb.
