### ISSUE TITLE
Limited to 1 form instance per form per page.

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1730]
When form is localized more than once on a single page subsequent instances do not render.

**Comment by kjohnson** [comment]
Also see: https://github.com/wpninjas/ninja-forms/issues/1455

**Comment by wpnzach** [comment]
Is there an estimated timeframe for this?  There were problems with multiple forms on one page before, but this presents in a much more obvious way and we're getting more requests about it than I'd expect.  Just wondering what kind of time frame i can offer up if one exists.

**Comment by kjohnson** [comment]
@wpnzach The best that I can say right now is 3-5 weeks if you want a timeframe. This will be a rather involved fix.

**Comment by andywhite8** [comment]
Is there any update on this as if it will still be a little while I will need to use a different forms plugin?
Thanks.

**Comment by jameslaws** [comment]
We have another report of this with different forms on the same page. It seems to be released to having tooltips on the form and the error I get is: helpText.js:12 TypeError: jQuery(this).jBox is not a function. (In 'jQuery(this).jBox("Tooltip",{theme:"TooltipBorder",content:jQuery(this).data("text")})', 'jQuery(this).jBox' is undefined)

If all tooltips are removed the forms all display just fine.

**Comment by kstover** [comment]
Different forms on the same page with tooltips works for me. If this is still an issue, we can re-open.

**Comment by isleshocky77** [comment]
@kstover I'm using _wppopupmaker_ which actually recommends using ninjaforms. And if I have different popups on the same page which pop open the same form, only one of the pop-ups will work. It appears that the lowest id popup will work while the other will popup with a ninjaform which just displays the loading indicator.

No error or logs appear anywhere for this problem.

**Comment by isleshocky77** [comment]
@kstover This issue should be opened back up since as the subject reads, this is not solved. You canNOT have more than one instance of a form on the same page. I completely understand it would take a fairly large rewrite to disconnect the frontend js from the backend db instand of the form; however, this issue is still not closed.

**Comment by leecollings** [comment]
Agree with @isleshocky77, this issue is not resolved.

If this is what I'm experiencing, I have one instance of the form displaying as expected, with the other instance opening in a modal. However when the modal opens, I just see a loading circle expanding in a loop.

I believe this is the issue correct? I am using both PHP functions `Ninja_Forms->display(1)` to show the form.

**Comment by jlambe** [comment]
@kjohnson as of Ninja Forms version 3.1.6, this issue is not yet solved.

Due to a mobile responsive issue, I have to render the same form on the page within 2 separate locations (div). The first met form is rendered correctly but the second one has the pre-loading icon animation running forever.

Any idea how to tackle this or if this is going to be solved soon?

**Comment by joelflint** [comment]
Ninja Forms Version 3.1.9 on WP 4.8 here.

I have a page with two different forms on it (newsletter signup, and contact). Both forms are rendering properly with different IDs (nf-form-1-cont and nf-form-2-cont). So the issues above in this thread could possibly be fixed. However, what I'm experiencing is that when error validation happens on one of the forms, it happens on both forms.

Not sure if this should be a separate issue or not, but it seems pretty related to me. Let me know if I can provide any additional information.

Thanks!

**Comment by isleshocky77** [comment]
@joelflint This particular is in reference to the same form (i.e. the same form id "nf-form-1-cont") being rendered more than once on a page. The reason it's a hard issue to solve is because all of the events are keyed off of this id and the way it's written it will only do it once. So the above issue has definitely not been solve - @kjohnson would love if this was re-opened just to keep track of if it is ever addressed.

The behavior you're seeing I have not seen before and I do have multiple different forms on the same page. You should be opening up a separate issue with your full details.

**Comment by pbov** [comment]
I also ran into this issue. We're using Divi-Theme where we build pages with hiding and doubling elements for different viewports. If I need to put in one form twice at a page, one form doesn't load.

Using two different forms is not the best workaround...

**Comment by jameelmoses** [comment]
Still an issue. I have the same use case as form rendered on the page, with another of the same in a modal.

**Comment by mynameiskyle** [comment]
Another vote to mark this Open. 

My use-case is we have a Newsletter form in the sidebar that is persistent but sometimes we want to put that same form inline as a speedbump in the article itself. As it stands now, one of those two forms will get the spinner.

**Comment by Shaxmax** [comment]
I also ran in this issue. Any updates on this?

**Comment by finks86** [comment]
same problem

**Comment by jnorell** [comment]
Still a problem in latest version 3.3.3.  My use case is gdpr export/request forms, they work fine in the sidebar for all but the actual privacy policy page, where the forms are also part of the page content - there the sidebar just gets the spinner.  Easy enough to work around, but please consider fixing.

**Comment by vashishtb** [comment]
Still facing this issue - can someone please advise why this issue's been marked 'closed' despite so many users facing the same issue?

**Comment by JiveDig** [comment]
Just hit this issue as well. Need to duplicate the same form (ugh) or approach this differently. Someone mentioned popup-maker to have different popups show the same form, this is a very practical use-case for this.

**Comment by dimic00** [comment]
So what ?!

**Comment by leecollings** [comment]
> 
> 
> Different forms on the same page with tooltips works for me. If this is still an issue, we can re-open.

Re-open it then...

**Comment by isleshocky77** [comment]
> Different forms on the same page with tooltips works for me. If this is still an issue, we can re-open.

@kjohnson It's your ticket, so I'm guessing you would have the best idea what this issue was supposed to address; however, the title of it suggests you were talking about a single form being added to a page more than once. No one who hits this issue thinks about "[multiple different] forms on the same page". 

I would suggest you either rename this issue and open a new issue with the same name which deals with the issue everyone believes this one is - or re-open this issue as it's clear that everyone is still hitting it.

Once again, I'll repeat what I said above; from my time working on the code I know this issue is a very big lift which requires a large refactoring of how a lot of the underlying code works - but it is definitely an open issue which is causing problems with multiple normal and usual workflows. 

Maybe their could be something more hacky which throws a check in to the inclusion to see if it's already on the page with some logic of when either are called... just a thought.

**Comment by oriooctopus** [comment]
This is still a problem, no?
