### ISSUE TITLE
No way to view all fields in form editor

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/ninja-forms#1744]
I noticed today that there are numerous fields available (such as the Password field) that are not shown in the form editor in any way unless you enter a search phrase for them.

Example with no password field:
![screen shot 2016-09-09 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/1034109/18402237/2528675c-76a4-11e6-958a-4320706ee488.png)

Filtered (ignore second password field, is from a custom add-on):
![screen shot 2016-09-09 at 3 43 32 pm](https://cloud.githubusercontent.com/assets/1034109/18402247/311bafa6-76a4-11e6-9562-eb552872aed6.png)

This is, in my opinion, a pretty poor user experience because the vast majority of users will never know that those hidden fields exist.

The concept of keeping less common fields out of the way is great, but there really should be a way to reveal those without being required to enter an explicit search term.

**Comment by chriscct7** [comment]
Before I open a seperate ticket for this it also looks like some of the fields (all three password ones and the county and multiselect ones) are missing icons. Is that intended or is it a bug?

**Comment by jameslaws** [comment]
Im sure Kyle or Kevin can comment on this better . But these are fields that are meaningless unless there is an add-on that uses them and knows what to do with them. Credit card fields are another example. Many different add-ins might need them so it makes sense for them to be in core. But they will only show up is the appropriate add-on that uses them is activated and applies the filter to make them available. 

For instance, credit card fields are hidden, but can be found by search. If Stripe is activated it adds a filter to show the credit card fields, because it know how to use them. There is no other reason to make these fields available. Then don't save the data and would not do anything the user might expect with out a credit card processing add-on. 

Passwords are the same way. We don't save that data to the submissions and unless they have an add-on that knows to use those fields to login, or create a WordPress user, why show them?

**Comment by pippinsplugins** [comment]
Ok then they should not be shown when filtered ;)

**Comment by jameslaws** [comment]
That's certainly not unreasonable. ;-)

**Comment by kstover** [comment]
@chriscct7 The additions of icons was a bit late in our Dev process, so not every field has an icon. There should be a default so that no field's is completely empty, but we haven't gotten to adding an icon for each. 

@pippinsplugins James is correct. With 2.9.x, we got tons of support requests when we had more advanced fields like password, credit card, etc in plain view. I'd rather keep them in the filter for advanced use-cases, but I'm not opposed to adding a method to reveal them all. I'm just not sure how to do that elegantly in the current UI.

**Comment by pippinsplugins** [comment]
@kstover does the `Password` field function in core or does it 100% require an add-on to do anything?

**Comment by kjohnson** [comment]
@pippinsplugins the `password` field is currently just a wrapper for a regular input (with a `type=password` template) which is used for the `passwordConfirm

**Comment by kjohnson** [comment]
Also, I think add-on dependent field type were only hidden so that the field definitions would continue to exist even when the add-ons were disabled.

However, the `unknown` field type was recently introduced which can make that consideration moot.

**Comment by kstover** [comment]
I've moved this onto our internal feature tracker. I agree that we should probably just hide those fields altogether unless they are enabled. We'll discuss what the best way of displaying all fields.
