### ISSUE TITLE
reCaptchas showing intermittently

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1805]
reCaptchas showing intermittently in 3.0
When this happens there are no errors in the console.

Here are the current cases for users having this issue:
https://wpninjas.desk.com/web/agent/search/cases?query=labels:recaptcha%20status:open

**Comment by klhall1987** [comment]
@jmcelhaney can you send me one or two users who are having this issue? I will need to be able to do troubleshooting on their site, so I'll need admin creds and they will need to be okay with me changing themes and turning off plugins to track down the issue.

**Comment by shinerweb** [comment]
I've been having the same issues and was about to submit a new ticket until I saw this.  I'd seen an other similar ticket where someone thought it might be related to server set ups etc.

My issue is across different browsers/two different server flavours.  I've tested the last 5 PHP versions up to 7.02 and it's repeatable.    I've also installed it on a stock install of WP with no plugins and still see the same behaviour.

Clear all caches, load up a form with a Captcha and without submitting any information or even before completing any fields, do a page refresh.  The actual captcha will disappear but leave the main heading.

I only delayed in submitting the ticket because I thought it might have been related to CloudFlare RocketLoader at one point, but then I hit the same snag on a non CloudFlare based domain.

There are no console or server errors, but what I have noticed is a whole section of the form isn't being output at all.  You have the outer DIV section which displays the captcha heading, but all of the internal form controls for the actual captcha just don't get output.   

I'll carry on digging and report back a little later.  Just wanted to add my £0.01 and confirm I'm seeing something similar to @jmcelhaney

**Comment by shinerweb** [comment]
Kenny,  here's a weird one.  When I enable the developer tools in Chrome, it fails less often.
If I switch on breakpoints and step through the code, I can't get it to fail and the captcha is always displayed.
Is there a chance of a race condition between requesting the captcha from Google, and the drawing of the form itself?  
I'm going to do some more digging around this area, I've been at this for a few hours so want to make sure I'm not barking up wrong tree and doing something daft.

I can give you access to a WP install that has the issue, (but even without any other plugins and on different themes it's still there so I'm pretty certain it's not plugin/theme related, unless something is having a timing impact etc etc).

Let me know if you'd like access and I'll set you up an account to login...

Chris

**Comment by klhall1987** [comment]
@shinerweb Thanks for all the information, that helps a lot. I won't be able to dig into this issue this morning. I'm currently working on another issue. But could you join our Ninja Forms Dev slack group? That would be the best place to get admin credentials for your site, this way you don't have to display any information publicly and it's a great place to keep up with what's going on with our product. I've added a link to our join page below. 

Ninja Forms Dev Slack Group:
http://developer.ninjaforms.com/slack/

Thanks, 
Kenny

**Comment by AdrienPoupa** [comment]
Same issue here. It does not display during first load, but is working fine afterwards.

**Comment by gpclarke** [comment]
I have 3.0.6 and I can't get the reCAPTCHA to display on my simple NINJA contract form.  See link: http://gotchadigi.com/contact-copy/

**Comment by dontpanic** [comment]
Issue still exists in 3.0.7

**Comment by tommyferry** [comment]
Bump. Issue still appearing in 3.0.11

**Comment by minznerjosh** [comment]
Same issue for my site, docsvoxshow.com.

I'm guessing it's some kind of race condition between the form rendering and the recaptcha script loading/initializing. So, in some cases, the recaptcha script is is initializing *before* the form is inserted into the DOM. If this is the case, using [explicit rendering](https://developers.google.com/recaptcha/docs/display#explicit_render) would probably fix the issue. I can look into fixing and sending a PR.

**Comment by kjohnson** [comment]
New reported case: https://wpninjas.kustomerapp.com/app/customers/582481e04e522a1000277d6f/event/582481e0e149e8120001d1b1

**Comment by kstover** [comment]
@klhall1987 @kjohnson @minznerjosh I just pushed a change to the `issue#1805` branch that explicitly renders the Google Recaptcha. It works for me locally, but I wasn't seeing the error before. I'd like to test on a site that is currently experiencing issues.

**Comment by leecollings** [comment]
Why was this closed? I believe this is still an ongoing issue, I experience this in multiple sites still.

**Comment by Fydon** [comment]
I'm also experiencing this issue. I see that `nfRenderRecaptcha` is in [assets/js/min/global.js](https://github.com/wpninjas/ninja-forms/blob/develop/assets/js/min/global.js) and [assets/js/min/front-end-deps.js](https://github.com/wpninjas/ninja-forms/blob/develop/assets/js/min/front-end-deps.js), but the function doesn't appear on my page.

**Comment by nicoHersant** [comment]
Hi everyone, also having the same issue here :` reCAPTCHA couldn't find user-provided function: nfRenderRecaptcha`
wordpress : 4.9.13
ninja formes : 3.3.19

**Comment by Fydon** [comment]
Last week I raised [this issue](https://git.saturdaydrive.io/_/ninja-forms/ninja-forms/issues/4283) on their main site, but haven't had a response yet.
