### ISSUE TITLE
"Confirm" field to ensure two fields match

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1818]
Needed for users who want to double confirm email addresses.  @kjohnson believes the code is already there and just needs extended to a "Confirm" field that can match any other field.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
