### ISSUE TITLE
Add new merge tag "Submission Link"

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#1846]
Would be great to have a new merge tag for submission links.

So that I can insert a link for administrators in email notifications. Like that, they can click on it and see the post item in wp-admin right away. Would make it a lot more convenient I think.

**Comment by kjohnson** [comment]
Should be simple enough to add.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
