### ISSUE TITLE
Allow users to set their own custom Default Value in the Country List

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1857]
Allow the user to specify the Default Value "Choose your County" rather than display the name of a county by default.

**Comment by bshuchter** [comment]
If possible, allow user to create the default value, which might be "Country", "Select Country", "Choose your Country", or anything else that might be appropriate to the user's design.

**Comment by kstover** [comment]
g]Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.

**Comment by jmcelhaney** [comment]
https://github.com/wpninjas/ninja-forms/blob/c2cf72107a02764cac0f67367307611de72a7361/includes/Config/CountryList.php
