### ISSUE TITLE
Provide option to move the success message below the form.

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1860]
Provide option to move the success message below the form instead above the form.

**Comment by kstover** [comment]
g]Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
