### ISSUE TITLE
UI for 3.0

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#187]
Hey

I am wondering if it is possible that you guys can share some screenshots (when available) on the way the UI for 3.0 is going so we can give feedback to the shaping of the next major version?

**Comment by kstover** [comment]
Several of these enhancements are in version 2.9, or have been moved around. We've since re-thought how we do feature releases, and this year should see a new major release every two months or so. Our team is growing, and I think we have a much healthier plan of attack.

Thanks again for your helpful comments. :)
