### ISSUE TITLE
Add option to fields to set the location of the required Fields Error message.

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1876]
Add an option to the field settings in 3.0 that will allow the user to set the location of the required Fields Error message.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
