### ISSUE TITLE
Add the ability to set the location of the description text

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1893]
In NinjaForms Version 2 we were able to place the description before or after the field box which was very convenient.

However, at the moment, if we set the label to "hidden“, then the description is automatically placed after the field box, which not very convenient.

It would be much nicer if we were able to set the position of the description independently of the position of the label.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
