### ISSUE TITLE
Add email attachment to email action

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1901]
We have a user requesting the ability to add attachments such as files and images to email actions.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
