### ISSUE TITLE
"Clear Succesfully Completed Form" option does not work

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1948]
When set, this option does not clear the form data.

**Comment by paqu83** [comment]
Hi wpnzach,
I can not reproduce this issue, can you pleas provide more details ?

**Comment by plecavalier** [comment]
I'm having the same problem and it's beginning to irritate me. What details do you need?

**Comment by plecavalier** [comment]
To start with here is a system info.
### Environment ###

Home URL:                http://BLOCKED.COM
Site URL:                http://BLOCKED.COM
Ninja Forms Version:     3.0.16
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache
PHP Version:             5.6.24
MySQL Version:           5.5.5
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           No
WP Language:             Standard
WP Max Upload Size:      500 MB
PHP Post Max Size:       500M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      2000
SUHOSIN Installed:       Yes
Server IP Address:       104.219.12.130
Host Name:               BLOCKED.COM
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/Toronto

### Plugins ###

Installed Plugins:       Black Studio TinyMCE Widget by Black Studio version 2.2.12
                         Ninja Forms - Layout & Styles by The WP Ninjas version 3.0.12
                         Ninja Forms by The WP Ninjas version 3.0.16
                         Page Builder by SiteOrigin by SiteOrigin version 2.4.16
                         Toolset Types by OnTheGoSystems version 2.2.2

Since I was using a somewhat complex form I created a defacto form using the "contact us" preset and turned off just about everything except advanced->display->clear if successful.

All that happens when I click submit is the send button turns to processing and then back to send. The form is successfully sent but never cleared. I've tried this in Chrome and FF on linux as well as Edge on Windows 10.

FWIW this has lived on through several version now going back about 3 or four months. I just upgraded to the versions listed above and it still persists.

**Comment by plecavalier** [comment]
bump

**Comment by jmcelhaney** [comment]
I was only able to replicate this issue with the Layout & Styles plugin active

Reproduction steps:
Have Ninja Forms and Layout & Styles active
Create a form with no redirect action
Set the option to clear the form on submission and disable the hide form option
View and submit the form and the fields do not clear


### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.20
WP Version:              4.7
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40M
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32M
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:       Ninja Forms - Layout & Styles by The WP Ninjas version 3.0.12
                         Ninja Forms by The WP Ninjas version 3.0.20

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/586bb13bac42cf10007bfd52/event/586bb13bac42cf10007bfd54

**Comment by plecavalier** [comment]
So glad to finally have this validated. Had no idea it was linked to layout & styles.

**Comment by kstover** [comment]
I'm going to move this issue to the Layout & Style repo, as it's an issue with that add-on.
