### ISSUE TITLE
Add new merge tag "Post Template Field"

### ISSUE THREAD

**Issue by lehtu** [wpninjas/ninja-forms#1991]
Hi, It would be nice if you could add possibility to use template fields in page or post.
For example if I there is pdf added to post and we want to send that to user only if they give us their email address.

Or atleast add possibility to add custom merge tags plz :)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
