### ISSUE TITLE
Allow merge tags on landing page

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1998]
In 2.9 we allowed shortcodes to be used on landing pages, but my understanding is the session needed to do this broke other things.  Would be nice to look into again in the future.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.

**Comment by wpnzach** [comment]
Still an issue

**Comment by kstover** [comment]
This is a feature request/enhancement. This can be really unpredictable, because it deals with PHP sessions or JS cookies.

**Comment by kstover** [comment]
I'm moving this over to our internal feature request tracker.
