### ISSUE TITLE
Suggestion: Clone/duplicate a row of fields all at once..

### ISSUE THREAD

**Issue by dud3sweet** [wpninjas/ninja-forms#2028]
It would be very convenient to be able to duplicate a row of fields that need to be repeated in a form instead of having to duplicate each field 1 by 1 or recreating each row from the list of default fields.

**Comment by kstover** [comment]
Do you mean in the builder using Layout & Styles?

**Comment by dud3sweet** [comment]
Yes, in the builder using whatever controls layout and styles in version 3.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
