### ISSUE TITLE
Allow custom fields to be completely hidden in the builder

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms#2030]
There are some use-cases in which you don't want the user to be able to add or remove a custom field from a form. Adding a $_section = "" protected properly removes a field type from the drawer, but not from the filter or other "all fields" functions in the builder.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
