### ISSUE TITLE
Add placeholder Option for Date Fields

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2070]
Currently in the 3.0 codebase there is not an option to set a Placeholder for the Date field.

**Comment by craigmdennis** [comment]
Also running into this issue.

**Comment by jameslaws** [comment]
We also need a default value. I have had another user request this.

**Comment by klhall1987** [comment]
[Vitaliy] (https://wpninjas.kustomerapp.com/app/customers/581ff9c805b06a11001470cf/event/58c25766e0a3041000b34404) Requested this as well.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
