### ISSUE TITLE
NF Database tables aren't created for a new site under WP multisite installation

### ISSUE THREAD

**Issue by tankadesign** [wpninjas/ninja-forms#2071]
I have Ninja Forms 3.0.14 Network Activated on WP 4.6.1 multisite. Created a new site and found that no new NF tables were created for that site, making it impossible to use NF on that new site. The Forms admin menu is there along with all the admin backend tools. But saving a form leads to no form data being created (and no errors that it couldn't create the form). Network Activate doesn't seem to create the tables at all, because I tried deactivating and reactivating from the Network Plugins panel. That did not create the tables. The only thing that works if you don't use Network Activation at all and individually activate the plugin within the site's plugin panel.

**Comment by jameslaws** [comment]
Ninja Forms does not currently support Network Activation and never has up to this point. Someday in the future we may make a pass act this, but at this time all we support is activating Ninja Forms on a per site basis.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
