### ISSUE TITLE
Exporting all submissions never finishes. WP4.6.1, NF3.0.15

### ISSUE THREAD

**Issue by karissa** [wpninjas/ninja-forms#2126]
There’s an option to download all but when I click on it I just get a message says "Lacing our Tabis 16%” for hours.

Exporting a single page seems to work fine, but there are 45 pages in total (881 submissions) and we need to export them all.

Any support very much appreciated.

**Comment by rwmichel** [comment]
I can confirm this.  Attempts to download submissions for larger/more complex forms and/or with greater numbers of submissions cause PHP fatal error due to memory exhaustion.  Normally, my php .ini has memory_limit=256M, wp-config has WP_MEMORY_LIMIT also set to 256M.  I could not even view the submissions list w/ pagination set in Screen Options to a very low value 10  for some of my forms.   After increasing to an unacceptably high 512M for PHP and WP, I was able to list all submissions, but with serious adverse impact on server performance.  Let me tell you, it was loads of fun exporting >400 submissions in groups of 10, one page at a time then concatenating the exported files.

**Comment by jameslaws** [comment]
This is a server resources issue that is exacerbated by the number of submissions we try to pull per step when building the file.

@kjohnson Change lines 33 and 63 in includes/Admin/CPT/DownloadAllSubmissions.php from 250 to 50 and I confirmed that this works in at least one users site.

**Comment by mpgilbertusa** [comment]
Are you sure that's the correct file to edit? I've just updated my Ninja Forms plugin to the latest and that file doesn't have anything like that.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.
