### ISSUE TITLE
Feature request: Switch field type directly in sidebar edit area

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#2134]
Hi

I just now began filling in a radio list and noticed that it would like nicer with a drop down. Being able to click the Radio List heading to switch it out the field with a drop down would be nice.

![switch--to-another-field-radio-list-ninja-forms](https://cloud.githubusercontent.com/assets/5323259/20515872/d98cd830-b093-11e6-9d4e-52a36e5a0dce.jpg)

That might mean having a small arrow next to the Radio List heading.

Use case: One begins to fill in the various areas of the Radio List and not to lose the information one could then switch to a drop down and keep the information intact.

**Comment by kjohnson** [comment]
This might work for "like" field types, but we would need some some conventions on what can be switched.

Example: Lists (checkbox lists, radio list, select list, multi-select)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
