### ISSUE TITLE
Star Rating field default value and required validation

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2158]
The Star Rating field defaults to a maximum value (ie 5 of 5) when user input is not provided. This subsequently means that the field bypasses required validation.

Instead, the field should probably default to a value of 0 (zero), or provide a setting to set a default value.

**Comment by Quay3** [comment]
FYI Kyle, we are receiving feature requests in Kustomer that the Star Rating field have a selectable default value.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
