### ISSUE TITLE
Timestamps!

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2159]
Related to https://github.com/wpninjas/ninja-forms/issues/334 https://github.com/wpninjas/ninja-forms/issues/446 https://github.com/wpninjas/ninja-forms/issues/504 

Add timestamps as a merge tag to be used as default vield values.  

Allow submissions to sort on timestamp instead of just date

Include timestamp in the CSV export

**Comment by isleshocky77** [comment]
I would vote for making three fields, Date (there now), Time, and Timestamp; although with `MergeTags` you could just do the timestamp from the date and time field.

Making the option of giving it formatting parameters would be really helpful, but as of now there is no way of passing `MergeTags` through a filter.

**Comment by klhall1987** [comment]
Requested by this user as well: https://github.com/wpninjas/ninja-forms/issues/2159

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
