### ISSUE TITLE
Datepicker and Opinionated Styles

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2177]
The datepicker does not currently support the light/dark opinionated styles.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
