### ISSUE TITLE
Enable tooltips on TinyMCE editors for better usability

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#2201]
As a usability suggestion, it would be great to have the TinyMCE tooltips enabled when hovering over controls:

<img width="304" alt="screen shot 2016-12-12 at 3 25 56 pm" src="https://cloud.githubusercontent.com/assets/522158/21117458/6d1c6390-c07f-11e6-923e-5f2ae6bbe47b.png">

As seen in the Post editor:

<img width="233" alt="screen shot 2016-12-12 at 3 25 45 pm" src="https://cloud.githubusercontent.com/assets/522158/21117466/763d8936-c07f-11e6-85b5-cdcffd6c80b0.png">

**Comment by kstover** [comment]
I'm not sure how Summernote (the RTE we use) supports this. We'll have to investigate further.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
