### ISSUE TITLE
Add 500 error handling for the Step Processor

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2206]
Port the 500 error handling code from form submission to the step processor to identify issues via error message.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
