### ISSUE TITLE
Add option for bulk delete of submissions

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2264]
Add option for bulk delete of submissions so all of the submissions for a particular form can be deleted.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
