### ISSUE TITLE
Ability to have a calculation be used in a hidden field to be saved (or just be saved without hidden field)

### ISSUE THREAD

**Issue by isleshocky77** [wpninjas/ninja-forms#2274]
It appears that currently calculations can only be on numeric values of the calc of fields. Also, calculations can only be displayed in the html type field and not used as a default of an input field.

It would be nice to be able to create a calculated field which is a concatenation of two or more string fields and then be able to be saved.

### Use Case

* Field 1
** Type: First Name
** Name: First Name
* Field 2
** Type: Last Name
**  Name: Last Name
* Field 3
** Type: Hidden
** Name: Full Name
** Default: {calc:full_name}
* Calculation
** Name: Full Name
** Equation: {field:first_name} {field:last_name}

**Note** I believe there a few issues stopping this from happening. One, is non-numerics in the calculations. Two, is the ability to use a calculation in a non-html field.

**Comment by adambloomer** [comment]
I second this. Why have a calculation function at all if you can't save it to the database or send it in a notification email?

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
