### ISSUE TITLE
Add an option to set the reCaptcha to a smaller size

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2297]
Add an option such as a drop-down to the reCaptcha settings to set the reCaptcha to a smaller version.
data-size attribute under the JavaScript resource (api.js) parameters
https://developers.google.com/recaptcha/docs/display#config

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
