### ISSUE TITLE
Export ALL forms' submissions

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2307]
> We are wanting to export all form submissions at once, rather than manually selecting each form and exporting the submission for just that form. - [Tim Lenton](https://wpninjas.kustomerapp.com/app/customers/5878fa47d6f7121100e6a1fa/event/5878fa472498d81000632ba9)

**Comment by dud3sweet** [comment]
In addition, it would be an improvement to be able to attach field data to the title of the submissions .csv file because if you export multiple submissions from the same day, they get the same filename and the only way to distinguish one from another is to open up each one and figure out who it belongs to based on the field data within. For example, on the submissions page for the specific form the user could input a file name: "[ninja_form_field id=123].csv". Also, automatic .csv backups of submissions with the filename customization to a local folder on the server would be awesome too!

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remedy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necessarily a development decision. This request has been transferred to an internal Trello board.
