### ISSUE TITLE
Indian Rupee

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2446]
User is requesting that we add the Indian Rupee as an available currency under per form Display settings.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
