### ISSUE TITLE
reCAPTCHA reset error on submission

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2454]
If the `grecaptcha` client_id isn't valid, then calling `.reset()` throws an exception. This is being caught by `submit.js` and looks like a broken for submission.

**Comment by Accuraty** [comment]
Months later, now Aug 17, 2017, I am running Version 3.1.9 of Ninja Forms and we are now getting this error sometimes, but not others.
 
I do not think the warning above the error is relevant because it appeared on page load. Whereas the grecaptch error appears immediately after clicking submit.
 
![image](https://user-images.githubusercontent.com/653301/29434562-14cfeee8-8369-11e7-8a9f-383e6825fc4a.png)
