### ISSUE TITLE
Add currency mask for calculations

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2467]
We have had several users request currency masks for calculations. For example instead of showing 1000 on the front end we would show $1,000.

**Comment by wssmichael** [comment]
I requested this over the weekend, but the request is inaccurate in the description. Actually the request was to add the currency mask for a regular numeric field (the calculations would be very helpful too). But my issue is that I am requesting a large dollar amount be input into a form with a "numberical" field.  It is very difficult for my users to enter large number like 10000000 without the commas for visual reference.

**Comment by wssmichael** [comment]
excuse the spelling / grammar.. typing fast

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.

**Comment by wssmichael** [comment]
this is the 3rd time i've received an email about this today... please i
get it, stop

Thanks,

Michael Barker
Owner - WorkSpace Solutions, LLC
(720) 432-0211
michael@workspacepros.com
http://workspacepros.com
