### ISSUE TITLE
Add extra "gate" to rollback option

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2520]
We need to make it extra, super, abundantly clear to users that if they roll back, nothing in 3.0 will be saved.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
