### ISSUE TITLE
Add a Clear button to form fields

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2523]
This was requested by a user today and looks to be something we had discussed under the 2.0 codebase but closed out when we upgraded to 3.0. Linking the old thread for consideration.

https://github.com/wpninjas/ninja-forms/issues/41

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
