### ISSUE TITLE
Product field in line quantity fields do not appear in submissions

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2527]
Product field inline quantity fields do not appear in submissions. This makes site admins have to calculate how many products a user purchases.

**Comment by EyesX** [comment]
Any quick fixes for this yet?

**Comment by jameslaws** [comment]
The quick fix is to not use inline quantities and use the separate quantity field that has a setting to attach it to a product field.

**Comment by klhall1987** [comment]
This is still an issue that needs to be resolved.

**Comment by wpnzach** [comment]
If we don't fix this, we need to remove the feature.  This has been urgent since March

**Comment by dstep2007** [comment]
Has this been resolved yet? I see the issue is closed, but I'm on version 3.2.8 (released Jan 4, 2018) which is after the close date and I still don't see this fixed in the email submissions.  What was the resolution to this?  This is very high priority for us.  Having to calculate quantities is a massive time waste and possible cause for a mistake in orders.
