### ISSUE TITLE
Field merge tags in HTML fields 

### ISSUE THREAD

**Issue by websbio** [wpninjas/ninja-forms#2536]
I couldn't find a feature request for this. We would very much like the ability to add merge tags to HTML fields. This would be very useful for complex multi-part forms where the user would be presented with key data for review before submitting.

**Comment by kstover** [comment]
The only issue with merge tags in HTML is that we'd have to create the convention for the merge tags to be updated "live" as the user fills out the form. At the moment, merge tags are completed in PHP during processing.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
