### ISSUE TITLE
Create option to force the redirect to open in a new tab

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2540]
Create option to force the redirect to open in a new tab

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
