### ISSUE TITLE
Add support for Google's new Invisible reCAPTCHA

### ISSUE THREAD

**Issue by JacobDB** [wpninjas/ninja-forms#2551]
Google just recently released their new Invisible reCAPTCHA, which aims to detect spam bots without any user interaction whatsoever. It looks really cool from a UX standpoint, and I'd love it if you guys could get this integrated in to your plugin. I think a setting when inserting the reCAPTCHA for "Visibility" would probably work great. Something like:

Visibility:

- Visible
- Invisible

The documentation for this is located here: https://developers.google.com/recaptcha/docs/invisible

**Comment by conomeda** [comment]
Any easy way to implement this in plugin code?

**Comment by JacobDB** [comment]
I'm not sure, but it should be pretty similar to the current reCAPTCHA. I'll try to look in to it this week.

**Comment by arcameli** [comment]
Happen to see if this can be implemented?

**Comment by JacobDB** [comment]
Sorry, I haven't had a chance yet. I've put it on my todo list for this weekend :)

**Comment by rossminney** [comment]
Looking forward to this Jacob! :) :)

**Comment by JacobDB** [comment]
Just took a moment to implement this, and submit a pull request. See #2638

**Comment by JacobDB** [comment]
Figured it out :) Needed to call `grecaptcha.execute()` manually in order for the validation to fire.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
