### ISSUE TITLE
If user removes field key, highlight error message directing them to enter a new key

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2553]
Currently, the styling on the error message when a field key is removed is not especially "loud" and can be easily missed at first glance.  Since it locks down the builder and makes it appear bugged, we need to direct users attention to the error more readily.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
