### ISSUE TITLE
Create function to grab our install's TLS version

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#2571]
- [x] Create the function
- [x] Hook into that function for our Get Help message

**Comment by double3** [comment]
@Much2tall -- i know this thread is closed and the code has been merged, but maybe you'll see this and can help. i bought the PayPal Express add-on for Ninja Forms today. after installing and activating, it gave me this error ... "Ninja Forms was unable to get your TLS version. Please contact your host and ask about updating your environment to support TLS 1.2 and HTTP/1.1." I contacted my host (Network Solutions) and they verified that both of those are already correct on my server. yet NF still says it can't detect the version number. they're not sure what to do and it might be a few days before i hear back on the support ticket i just submitted to NF. any ideas while i wait? i gotta imagine that something on the Network Solutions side is preventing NF from pulling the TLS version. because i was able to install the plugin just fine on a different host (SiteGround). ???
