### ISSUE TITLE
Need Default Value setting for selection type fields

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2584]
Fields like State, Country, Multi-Select, Checkbox List, Radio List, etc do not have the Advanced setting present to allow users to input a Default Value.

A number of users both in our support queue and blog have been requesting this as a feature that is important to their individual use cases. 

This has been input as a featue request in the past but with a narrower focus [https://github.com/wpninjas/ninja-forms/issues/1857]. Reiterating that here with a broader scope as we are continuing to get requests for this feature.

**Comment by kjohnson** [comment]
List fields have a 3rd list open for "selected", which is a checkbox. This can be used to select default values.

"Label", "Value", "Selected".

Also, the Country field should have a setting for "Default Value", being that it is not a typical list field.

**Comment by gandrewnorman** [comment]
This still doesn't really explain how users can pass drop down information from one form to the next. Based on your logic above, how am I supposed to dynamically check the "Selected" state selection box for each user that fills a form? 

Example of use case... User fills out personal info form. This form has address form fields. I want to pass the selected State from this personal info form to the next form using default values (like the rest of the single line text fileds have) but I can't...because the list fields do not have a  "DEFAULT VALUE" field to add your custom key to. 

If I am missing something here, please add that missing something to your docs so users like me do not flounder around with issues like this.

**Comment by agpreynolds** [comment]
I also feel there is an issue here. I am using the user management add on and specifically the update profile action. This allows me to pre-populate my form with existing user data by assigning an input to a data item.

This works perfectly until I map my billing_country to a country field. The field always takes the default value as set in field configuration, ignoring the currently selected value.

For the time being I have had to get around this by making country a select field

**Comment by joelworsham** [comment]
I too request this. Specifically for the ability to populate with a query parameter. The 3rd list open for "selected" is not sufficient for this use-case.

**Comment by Nic72** [comment]
I too request this, in fact I think it is required. For example the essential and very simple "Form of address" select field (with just two values "Mr." and "Mrs.") can not be created with the "User Management" add-on because it is not possible to pre-populate the select field with the stored value :(
