### ISSUE TITLE
Add option to view all submissions to the Submissions screen

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2616]
Add option to view all submissions to the Submissions screen

**Comment by isleshocky77** [comment]
@jmcelhaney Why did you close this issue? I was looking for the same Feature Request and found this, but then found you closed it for no mentioned reason.

**Comment by jameslaws** [comment]
It was likely closed because it was discussed and decided that it's not something we are going to do. Displaying all submission from all forms in the same table doesn't make a lot of sense and isn't really possible since every form can be made up of data that is unlike any other form. This is not conducive for a tabled display.

**Comment by isleshocky77** [comment]
@jmcelhaney Most of my forms have very similar if not identical data. It would be very helpful to see all of it at once. You could start with having all columns who's _Admin Label_ is the same turned on with the rest optionally hid from the view menu as it is now.

Do you think you could re-open the issue and I might put a PR in for it for you guys to review when I have a chance.

Thanks.
