### ISSUE TITLE
Allow users to change checkbox submission values

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2637]
Currently when a checkbox is submitted the value in the submission is "checked/unchecked" we have had several users who want to change this value. We should add a field setting to do this.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
