### ISSUE TITLE
Add feature for line breaks/separators for list fields

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2649]
I've seen a number of requests in the support queue from individuals using long list fields. They'd like to be able to add line separators, ideally with the ability to label these separators, in list fields to divide a single list into sections. Just throwing it in here as a feature request for your consideration on their behalf.

**Comment by kjohnson** [comment]
For now, we offer a hook to modify a field value before it is added to the Fields Table merge tag:

`ninja_forms_merge_tag_value_{field_type}`

This is a filter convention that is built dynamically.

**Comment by kstover** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues.

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
