### ISSUE TITLE
Add a merge that pre-populates user meta in fields

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2652]
Ad a merge tag that pre-populates user meta in fields on the front end. This is a feature in [Gravity Forms](https://www.gravityhelp.com/documentation/article/merge-tags/#user-meta) and it probably wouldn't be a bad idea for us to add this.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
