### ISSUE TITLE
Apply target="_blank" to media uploads/links in HTML fields. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2655]
Right now if a user has an a media upload or a link in a HTML field, when the link is clicked it loads on the page that the user is on and they lose all their form data. We need to apply target="_blank" to any links and uploads to prevent this.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
