### ISSUE TITLE
Persistent change tracking

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2673]
Yeah I know this is a big one. But would be great and helps a lot when investigating why things go wrong. Here a real world scenario @kjohnson and I have experienced:

1. The client complained a form not working properly
2. I have spent more than 20 min investigating
3. Then it turned out that the problem was something totally different: some actions in the form were disabled.

Grrr, someone must have disabled them for some reasons. No idea who. Would be great to keep track of persistent changes such as who disabled the action X, so that I can tell the person not to do this anymore.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
