### ISSUE TITLE
Hiding reCAPTCHA with Conditional Logic

### ISSUE THREAD

**Issue by heathhouston** [wpninjas/ninja-forms#2708]
When you hide/show reCAPTCHA with the conditional logic, it doesn't show.

**Comment by kjohnson** [comment]
Hm, the reCAPTCHA field wasn't designed to be hidden/show. The typical use case is to be shown all the time.

What is your use case for showing/hidding the reCAPTCHA conditionally?

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.

**Comment by crmpicco** [comment]
I'm interested to know if this feature has been implemented or if it is on a roadmap.
