### ISSUE TITLE
Some characters are being encoded incorrectly on conversion. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2717]
Some characters are being encoded incorrectly upon conversion. Here are some of the characters that I have found that are broken, I'm sure there are others. „ä“, „ö“, „ü“ and „ß

**Comment by klhall1987** [comment]
This is still an issue.

**Comment by Much2tall** [comment]
> Hey
Recently i install `ninja forms 3.1.4`, and i found issue in unicode text, in my case i used 
persian text `تماس با ما` for my field label, and after export and import my text was weird! like this `ØªÙØ§Ø³ Ø¨Ø§ ÙØ§`
please fix this issue.
php ver: `5.6.30`
ninja forms ver: `3.1.4`
wordpress ver: `4.6.6`

**Comment by cedriccharles4** [comment]
Hello ! Same here with french text. All the characters with accent are being changed to weird code... It happens when I convert existing form to from NF 2.x to NF 3.x.
For example these characters are changed : 

- é
- ù
- à
- è
- ...

Steps to Reproduce:
Create a form in ninja form 2.x and add some chars with accents. Example : "é". Than, update to THREE. The "é" char will be replaced by weird characters...

Thanks !

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5925be060d39a200119e10b9/event/5963be4e6b8bea001163018a
