### ISSUE TITLE
Add ability to pass default field values through shortcode

### ISSUE THREAD

**Issue by isleshocky77** [wpninjas/ninja-forms#2728]
It would be nice to be able to set the default value of a field through a shortcode.

## Example

```
[ninja-forms id="1" formsource="Homepage"]
```

**Comment by kstover** [comment]
I think that this would be a great idea, but not sure when we'd be able to get it implemented. Pull Requests welcomed. :)

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
