### ISSUE TITLE
New display option for inputs: readonly

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2729]
I have a case here where I want to display an input so that a merge tag is visible to the user but cannot be changed with the readonly HTML attribute.

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
