### ISSUE TITLE
Update the Advanced > Conditional Logic to use MergeTag selector for "Field"

### ISSUE THREAD

**Issue by isleshocky77** [wpninjas/ninja-forms#2734]
This would allow the current functionality of having a conditional based on a field, it would also allow for a conditional to be based on a combination of fields as well as other merge tags such as query_string.

**Comment by kstover** [comment]
This isn't something that we can do because Conditional Logic expects that the value of a condition is always the key of the field. Using the merge tag system would be great for some users, but would make it much too easy to break the condition for a majority of our users. This would increase the amount of time we have to spend in support for Conditional Logic.
