### ISSUE TITLE
Retrieve merge tag values via JavaScript

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2745]
Would be great to implement endpoints so that ninja-forms addons, which are heavily written in JavaScript, can retrieve merge tag values for further reuse. Even those merge tags which aren't field based like `{wp:admin_email}` or `{wp:site_name}`.

**Comment by jameslaws** [comment]
feature

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
