### ISSUE TITLE
Feature Request for Pound Sterling. 

### ISSUE THREAD

**Issue by MongolianMisfit** [wpninjas/ninja-forms#2752]
User: **"I spent ages trying to find GBP£ and thought you didn't support it. I would suggest you either add £ to 'Pound Sterling' or Add 'British Ponder Sterling'. Thanks."**

**Comment by jameslaws** [comment]
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed because we have decided not to maintain feature requests inside of GitHub as it’s a business decision and not necesarily a development decision. This request has been transferred to an internal Trello board.
