### ISSUE TITLE
Deregister/dequeue unnecessary styles on our admin page

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2933]
WP does have a way to remove scripts...but is there a way for us to remove all scripts except for ours and the admin?  Other plugins loading styles in our builder causes a lot of styling issues and makes our product look super broken.

**Comment by Much2tall** [comment]
@wpnzach 
I believe it's generally considered bad practice to do this because you're disregarding other plugins' settings, but as far as I know, it is possible.
If I remember correctly, @kjohnson was looking into building something like this as a "dev mode" that we could use to check for plugin conflicts.

**Comment by wpnzach** [comment]
The issue is that is significantly impacts the builder and builder functionality for these users.  It makes Ninja Forms appear super broken, causes support issues, and is additionally a pain for support to work with when it occurs.  If it can't be done, that's one thing...but if there's a way to do it, it would be really valuable to do.

It's against standard practice, but so is taking over the WordPress admin.  This is a consequence of us making that choice, so I'd really like to look into a way to preserve our styling if it can be done.

**Comment by wpnzach** [comment]
closed in favor of #3041
