### ISSUE TITLE
Sort on column headings in submission view

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#3032]
This has been requested by a few users.

**Comment by kstover** [comment]
When submissions are moved out of a custom post type display, this may be possible in-plugin. For now, we recommend using Admin Columns Pro, which lets you sort submissions.

**Comment by jameelmoses** [comment]
Instead of forcing people to pay for a premium plugin to apply a simple filter to make this work, why not just apply the {{manage_$post_type_sortable_columns}} filter.

https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_$post_type_sortable_columns
https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_edit-post_type_columns

I'm happy to make a PR if there's a chance of it being merged in.
