### ISSUE TITLE
Pre-processing Submission Limit Check

### ISSUE THREAD

**Issue by Much2tall** [wpninjas/ninja-forms#3070]
The Submission Limit currently processes on Form load.
However, it is possible for multiple users to open up the Form when the limit has not yet been reached and then both submit the Form, pushing it **over** the limit.

Submission Limit needs to be checked during processing and the Form should be kicked back if the limit has already been reached.

Steps to Reproduce:
1. Create a New Form
2. Add a Field
3. Give the Form a Submission Limit of 1
4. Publish the Form
5. Preview it in two separate tabs
6. You can submit both of the tabs, and they will process, even though the limit is set to 1

**Comment by thewebtailors** [comment]
The submission limit still only gets checked when the form is being loaded. I run into this issue today with a Ninja event registration form. 19 registrations were submitted after the form software should have cut it off.
Please fix this since this makes it almost impossible to use Ninja Forms for events registrations where the registrations are limited.
