### ISSUE TITLE
UX Suggestion - Change Label "Store Submission" to "Save Submission"

### ISSUE THREAD

**Issue by devinsays** [wpninjas/ninja-forms#3127]
I'm developing for a WooCommerce shop, so the "Store Submission" label was a bit confusing until I read the doc on it. "Save Submission" or "Keep Submission Record" might be clearer? Small thing, and the doc link was right next to it (which is great), so feel free to close if you disagree.

![screen shot 2017-10-05 at 10 16 14 am](https://user-images.githubusercontent.com/431879/31235511-54945a9a-a9b7-11e7-9ac0-20d0c3d2eb3b.png)

**Comment by Much2tall** [comment]
@devinsays 

This particular change was made as a result of us releasing our Save Progress add-on.
In order to differentiate between a Save and Submission to our users, we opted to re-title our previous Save Submission Action to a Store Submission Action. This allowed us to show a communicate a visible difference that wouldn't confuse our users.

Thank you for pointing it out though. We'll take some other options for this text into consideration for further clarity. No guarantee it'll change from what it is, but it is worth thinking about.
