### ISSUE TITLE
Bug on uninstall, the wp_nf3 tables is not removed from database

### ISSUE THREAD

**Issue by choquo** [wpninjas/ninja-forms#3220]
When i uninstalled the plugin all the wp_nf3 tables remain into the database.

**Comment by Much2tall** [comment]
@choquo This is a feature to prevent you from losing data when you re-install the plugin.
In order to remove all Ninja Forms data, we've provided an option under Ninja Forms -> Settings -> Advanced Settings -> Remove ALL Ninja Forms data upon uninstall.

If you check the box there and save your Ninja Forms Settings before you uninstall, it should remove all of the tables.

**Comment by Much2tall** [comment]
Closing issue as this repository is for known bugs in the software.
