### ISSUE TITLE
numeric custom input mask breaks with 13+ characters

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#3263]
When entering 13+ characters for a numeric custom input mask (ex 9999999999999) the field viewed on the front end will contain that number of numerals with the first digit being 1 and the rest 0 (ex 1000000000000).

Reproduction steps:

- create a form with a single line text field
- for that field, set a custom input mask for numbers only with 13+ digits: 9999999999999
- preview form: field contains the value 1000000000000 and will not accept user input

**Comment by Much2tall** [comment]
This is expected behavior, as it is the limit imposed by autoNumeric.
We couldn't identify a use case that would require accepted input to ever be above this number. So, it has never been addressed.

@Quay3 
Could you please describe the use case in which you would need the ability to enter a number this large?

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5a345baa98d8770001156ab1/event/5a38bdcbfa3c46000106f132
