### ISSUE TITLE
no import csv submissions?

### ISSUE THREAD

**Issue by j4jes** [wpninjas/ninja-forms#3391]
I have just exported my submissions to CSV and noticed they are in ascending order with newest on top. I have 100+ old entries from a previous system that I have added to the CSV document in ascending order, trying my best to keep the same format fields and columns. I guess I assumed there was an import submissions, seems logical if there is a download submissions. Now I'm stuck possibly having to enter these 100 entries manually !!

**Comment by wpnzach** [comment]
Ninja Forms isn't currently meant to be a CRM-type solution.  This is  a request we've seen a few times, so we're considering it in the future, but at the moment we don't intend for submissions to be a place to store business data permanently, or a place to need data imported into, which is why this isn't currently a feature.
