### ISSUE TITLE
Success message position always above form

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#342]
Ignores user setting, always above form.

**Comment by kstover** [comment]
I'd like to get a fix in for this, but there are a couple of challenges that I can think of:

1) We'd need to create a response div above and below the form, presumably with the same ID, but suffixed with _top and _bottom. This would mean that anyone who is currently targeting the success message by ID for custom CSS or JS would lose their customisation until they fixed the reference.

2) The JS would need the most work, since it would need to know which div to target if the form was submitted via ajax.

**Comment by UVLabs** [comment]
Something so important has yet to be implemented...this is done in Contact Form 7 by default
