### ISSUE TITLE
Browser autocomplete is off. Is there a way to turn it on? 

### ISSUE THREAD

**Issue by cmendla** [wpninjas/ninja-forms#3428]
- **What actions are you taking?**
Browser autocomplete is not working. This is problematical for emails. Apparently issues #231 and #2171 requested the ability to turn the browser autocomplete off. From what I can see it is off but I don't see a way to turn it on . This poses a problem for users on mobile devices. Worst case, stanislaus..pavel.wochiezski@mylongdomainname.com has to type his address in on his android instead of using the browser autocomplete. 

 - What had happened was... 
no browser autocomplete

- **What are you expecting to occur?**
Browser autocomplete. 

1. Is there an option to turn browser autocomplete  on ? 
2. If not, can this be added as an enhancement? 

thanks, Chris

**Comment by wpnzach** [comment]
The issue is more complex than just enabling autocomplete, unfortunately.  Currently, Ninja Forms 3.0 doesn't output form tags.  As a result, even with autocomplete enabled, it doesn't work in any modern browsers.  When form tags are added, other issues occurred causing breakage.  This is being looked into, but ended up being more complex than originally thought.  We should be about a month out.

**Comment by tantuohy** [comment]
So has anyone implemented a successful workaround?

**Comment by AdilAliUK** [comment]
I am also having the same issue, I'd love to know when this will be updated.

**Comment by modelm** [comment]
For those tracking this issue, it looks like 3.2.17 includes autocomplete according to the changelog on https://wordpress.org/plugins/ninja-forms/#developers : `Form autocomplete is here!`
