### ISSUE TITLE
Update failed, plugin disappeared. Now error occurs when trying to re-download

### ISSUE THREAD

**Issue by Tahliamorgo** [wpninjas/ninja-forms#3491]
My Ninja Forms update failed on my WordPress site and then the plugin disappeared from my plugin library. Now every time I try to re-download the plugin it comes up ‘Installation failed: Destination folder already exists.’

**Comment by shinerweb** [comment]
Log in via FTP or your cpanel and navigate to your plugin folder.
Rename or remove your old ninja forms plugin folder.
Then reinstall ninja forms via WordPress admin.
You won't lose any data, it'll still be there in your database.

WordPress will automatically disable a broken plugin preventing it from running.
You can't install again as the folder still exists it states but if you manually remove it, you can then reinstall it.
The update could have failed part way through an update.  I doubt this was in anyway due to ninja forms itself.

**Comment by wpnzach** [comment]
Thank you @shinerweb for the assistance here!
