### ISSUE TITLE
Why did NF choose to go to a non-semenatic version numbering scheme?

### ISSUE THREAD

**Issue by jschrab-lc** [wpninjas/ninja-forms#3629]
For the most recent patch, 3.3.14.1 was created and not 3.3.15. Why the change away from [semantic versioning](https://semver.org/)? Our Composer plugin management/deploy was kinda depending on a consistent numbering convention.

**Comment by Much2tall** [comment]
@jschrab-lc 
We apologize for any inconvenience this might have caused you, but if you look back through our tag history, you can see that appending the additional .1 isn't a new convention for cases where we specifically released a security patch with no additional features or bugfixes.
As of the next release, we will switch the versioning back to the expected behavior, but we can't guarantee this versioning convention won't reappear in the future, should we encounter another situation where we need to roll out a swift security hotfix.
