### ISSUE TITLE
Link two form fields for JS purposes

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#456]
Similar to how the the calc functions work, if something happens to A then something will happen to B. Right now there is a lot of moving around the DOM to find what you want. 

	$( ".field-wrap" ).on( "change", ".currency", function() {
		var form_num = unformat_price( $(this).val() );
		$(this).closest('.field-wrap').next('.calc-wrap').find('.ninja-forms-field').show().val(form_num);
	});

**Comment by kstover** [comment]
There isn't much we can do about this at the moment; I have it on my calendar to re-examine our front-end JS later this year. This will include a re-write of the logic of calculations, conditional logic, and adding some jQuery events that fire when a field changes, so that it can be easily hooked into.

**Comment by helgatheviking** [comment]
Ok. I was able to do it with form field IDs, it is just that it is just that you can't re-use the jS on other forms of a similar nature.

**Comment by kstover** [comment]
Yeah. We're going to be adding a "key" option to fields in the next feature version. This would let you target by "key" rather than id. This would make your custom code much more portable.

**Comment by helgatheviking** [comment]
Dig it!

**Comment by kstover** [comment]
This is coming in version 3.0.

**Comment by kjohnson** [comment]
v3 introduces field keys and a Backbone radio system for interacting between fields.
