### ISSUE TITLE
Custom triggers for notifications

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#458]
Currently all the notifications are triggered on the `ninja_forms_post_process` hook. It'd be pretty sweet if the notification class could set its own trigger. For example, if you get a valid IPN notification from PayPal you might want to do something *then* and not on the default hook. 

```
// Add our hook to add notification types processors.
add_action( 'ninja_forms_post_process', array( $this, 'notification_processing' ), 999 );
```

**Comment by kstover** [comment]
Hey @helgatheviking,

Thanks for the suggestion! We are actually changing the name of the "Notifications" tab to "Emails & Actions." Eventually, all of our extensions will be moved over to using that tab for their processing actions: i.e. Post Creation, Newsletters, etc.

When that time comes, the hook they run on will be more customizable, although it will still hook into either pre_process, process, or post_process, because those are the three hooks that fire when a form is submitted. So, even if PayPal did somthing special and added its own action hook, it would eventually trace back to one of those hooks, if that makes sense. I agree that it would be nice to have customizable hooks for the actions.

**Comment by helgatheviking** [comment]
Well a PayPal IPN notification would `http://example.com?paypay_gateway=1` with a bunch of data, but not necessarily on post_process. It would depend on when the payment went through, so if you could somehow allow for totally custom hooks, that could be pretty powerful for all the payment processor extensions.

**Comment by kstover** [comment]
Sure. The core plugin needs to be agnostic about extensions, but we could modify the notifications class so that the action could be overwritten by each notification that extended the core class. It would default to post_process, but could easily be changed within the child class.

**Comment by helgatheviking** [comment]
Of course! But if you can set your own trigger, you can leave it up to the
child class to handle it however it wants.

**Comment by kstover** [comment]
Yup. That's what the above would allow.

**Comment by eduardoarandah** [comment]
Hi! 
I'd like to integrate pushes via pushbullet. 

When user submits a form, execute some PHP code.

What is the best way to do it? 

What hook is better? (assuming that email may fail sometimes and maybe hooks after that could fail)

Do you have an example?

**Comment by kstover** [comment]
This would be easy to implement, I think, but we'd have to be careful about how we asked devs to implement it in their actions for consistency. We need to think about it a bit, but I don't see why this couldn't be something we add in the nearish future.

**Comment by helgatheviking** [comment]
I was toying with this at the end of last week. Then I was away for the weekend, and got back yesterday with a hella migraine. Anyway, I'd like to get back to it this week. I think you're right that it won't take a lot of work on the NF side... basically just a way to disable the action auto-firing on the `ninja_forms_post_process` hook.

**Comment by eduardoarandah** [comment]
In the real world, at some point, after thousands of submissions, the next natural step is processing the output in a more efficient way.

That next step is out of scope for wordpress and NF. 

That's why I think post-processing hooks (and examples) are important.

**Comment by kstover** [comment]
Hey @eduardoarandah,

Somehow, I missed your comment from March! I'm very sorry!

The best way to do this would be to create an action using our action API. (Currently, most of the code is called notifications because of an old naming convention.) Good examples are: ninja-forms/classes/notification-email.php, notification-redirect.php.

These will add new action types that can be added to any form processing.

**Comment by helgatheviking** [comment]
Might make a good addition to NF3.0

**Comment by kstover** [comment]
We've actually been discussing how we are going to approach the actions system and processing in 3.0. Once we have something concrete, I'll be posting about it with some details.
