### ISSUE TITLE
Allow error messages for NF settings

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#464]
Currently, you can only display an update. But I'd like to be able to display an error message.

```
if( isset( $ninja_forms_admin_update_message ) AND $ninja_forms_admin_update_message != '' ){
	?>
	<div id="message" class="updated below-h2">
		<p>
		<?php echo $ninja_forms_admin_update_message;?>
		</p>
	</div>
<?php
}

**Comment by helgatheviking** [comment]
And while we're at it, being able to pass HTML markup would be a plus too.

**Comment by helgatheviking** [comment]
Why not use the Settings API for messages?

**Comment by kstover** [comment]
We created the whole Ninja Forms tabs and metabox system before we got into the settings API. It would be nice to have all of our settings stuff moved over, which is why we recommend that third-party devs use it instead of our home-grown version: "Use the WordPress API for these settings that aren't form specific. Ninja Forms currently offers its own method of adding and saving options. In the future, this will be depreciated in favor of the WordPress options API."

**Comment by helgatheviking** [comment]
Ah ok, so then I am going about this wrong. I had wanted to move my settings into a tab though instead of its own `add_sub_menu()` page. Is that not a good approach? Or should I put it in a tab, but still using the settings API. Though I won't be able to show messages above the tabs. Settings API for NF 3.0! :) Because I'm sure you don't have enough things to do.

**Comment by kstover** [comment]
Ha! Currently, I think the best solution would be to create your own submenu for settings. We have some thoughts on how to simplify extension settings, which we'll divulge at a later date. :)

**Comment by helgatheviking** [comment]
I will wait to change that until you have a better framework in place.
