### ISSUE TITLE
Doesn't the cache need this directive? define('DONOTCACHEPAGE', true);

### ISSUE THREAD

**Issue by eduardoarandah** [wpninjas/ninja-forms#483]
This line:
define('DONOTCACHEPAGE', true);

Tells caching plugins to not cache the resources, I looked for this directive in source files but didn't find it. 
How does the plugin handle caching? (w3 total cache, super-cache)

**Comment by wpnzach** [comment]
We have looked into doing something like this and we're not opposed to doing this at all, but the issue is that there doesn't seem to be a standard across all caching plugins.  We would like to investigate and cover the top handful of caching plugins in this manner, but there's not a way for us to catch all of them that I have seen.

**Comment by eduardoarandah** [comment]
I know, I've tested it with w3 total cache and super cache and works fine!

I implemented it in wp-form-manager and solved issues with caching.

In this plugin I dont understand how the Ajax post is made, so I prefer not
to do it myself and break it =)

El viernes, 27 de febrero de 2015, wpnzach <notifications@github.com>
escribió:

> We have looked into doing something like this and we're not opposed to
> doing this at all, but the issue is that there doesn't seem to be a
> standard across all caching plugins. We would like to investigate and cover
> the top handful of caching plugins in this manner, but there's not a way
> for us to catch all of them that I have seen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpninjas/ninja-forms/issues/483#issuecomment-76460095>
> .
>


-- 
Enviado desde mi móvil
