### ISSUE TITLE
Extension Compatibility Notifications

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#565]
Add notices for extension compatibility checks.

**Comment by pippinsplugins** [comment]
Any thoughts on how this works yet? Will there be a formal API for it?

**Comment by kjohnson** [comment]
The basic idea is to start with version compatibility with core to notify users about needed updates.

**Comment by kstover** [comment]
@pippinsplugins This would be a change to the extension license class. Instead of extending the extension license class from core, devs would "register the extension" with an extension class, passing a "required Ninja Forms version" as a param. Then, the core plugin would prevent a core update if the extension wasn't compatible with that version of core.

**Comment by pippinsplugins** [comment]
:+1:
