### ISSUE TITLE
Field option to toggle submissions columns

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#570]
Currently there doesn't seem to be a way to force certain fields into columns for the submissions admin table... well not from the UI... I have found the filter. What if this were an advanced field setting right next to Admin Label?

Some columns are added automatically via the [change_columns()](https://github.com/wpninjas/ninja-forms/blob/master/classes/subs-cpt.php#L289-L294) method. I've never really been able to figure out why some field types have "process_field" as true and some don't, so using that as the determining factor for being a submissions column is confusing for me.

**Comment by kstover** [comment]
The process_field setting is really just a "Should this be stored in the database when a submission is saved" flag. Submit buttons, for example, aren't processed, so that flag is set to false.

I'm not 100% sure what you mean by forcing certain fields into columns. Could you be more specific? You can add/remove fields from the columns by going to the "screen options" setting at the top.

**Comment by helgatheviking** [comment]
SO MUCH FACEPALM it should be a  :facepunch: Screen options strike again. For some reason I thought I couldn't get totals or radio buttons in the columns, but they were hidden the whole time!
