### ISSUE TITLE
Conditional logic light built in?

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#573]
Hey

I have a customer that needs some light conditional logic as is this the billing address. If yes then no extra box opens if no then another set of addresses boxes opens up. Just the standard stuff for filling out purchase information.

Is there a simple solution to hide a set of fields in Ninja Forms without having to get a hold of the Conditional Logic extension? I am thinking a kind of conditional logic light built into Ninja Forms or some hacks to get the above example to work.

Since my customer is using contact form 7 I searched and found this thread: 
https://wordpress.org/support/topic/contact-form-7-with-options?replies=4
So I am thinking I can use something like this for Ninja Forms..... Or I can always just test it out with Contact Form 7 and see how it goes. I am working on getting her over to Ninja Forms.

Have a great day!

ps
At one point I will make a video tutorial of Ninja Forms. Not sure yet when. Do let me know when you guys get eager to get a video tutorial created.

**Comment by kjohnson** [comment]
A similar solution would work, yes, using custom JavaScript. But the Conditional Logic extension does a lot more in the background than just show/hide fields.

**Comment by kstover** [comment]
This isn't something that will be moved into Core because, as Kyle alludes, there is more going on than just hiding and showing fields. (We have to think about things like editing submissions, what gets stored in the database, shortcodes, etc.) The amount of moving parts means that we get a good amount of support tickets for Conditional Logic. Adding this into Core would dramatically increase our support load, and I'm afraid that we couldn't sustain it over a large, free user-base.

**Comment by paaljoachim** [comment]
Alrighty thanks for the answers Kyle and Kevin! I appreciate the response! I'll look into the hack and the extension. Have a great day!
