### ISSUE TITLE
Password value not stored in submission, is this expected?

### ISSUE THREAD

**Issue by sumobi** [wpninjas/ninja-forms#721]
I've created a simple form with a password field. Upon submission the value of the password field is not stored in the form submission, inside the admin:

![screen shot 2015-05-27 at 5 26 08 pm](https://cloud.githubusercontent.com/assets/52581/7829401/7ff2c4d4-0495-11e5-9d61-19b8d491925e.png)

However if I add an email action, the password ("hello" in this example) is sent fine in the email

![screen shot 2015-05-27 at 5 25 49 pm](https://cloud.githubusercontent.com/assets/52581/7829402/7ff8048a-0495-11e5-840c-aa4a71a9d840.png)

It isn't however stored in the .csv file attached to the email:

![screen shot 2015-05-27 at 5 28 00 pm](https://cloud.githubusercontent.com/assets/52581/7829424/c79e41be-0495-11e5-85fc-66db15646703.png)

Is this by design?

**Comment by kjohnson** [comment]
@sumobi this should be expected behavior.

The Password Field Type is registered with the argument `save_sub` set to `false`, see [password.php](https://github.com/wpninjas/ninja-forms/blob/master/includes/fields/password.php#L22).

Also, the `save_sub` value defaults to `true`, see [register.php](https://github.com/wpninjas/ninja-forms/blob/57f3820fb4d9b04545e3cdc065e417c16668dc20/includes/register.php#L47).

**Comment by sumobi** [comment]
@kjohnson Thanks for clarifying!
