### ISSUE TITLE
Form Builder - Mobile Responsiveness

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#788]
Fields in form builder are static width, breaking the responsiveness of the form builder in the backend.  See the user submitted video here: https://www.dropbox.com/s/csyu9urwezxudyl/quickcast-12-07-2015-11-45-57.mp4?dl=0

**Comment by jameslaws** [comment]
I'm not sure this is anything that we would fix in it's current state. The reason is that it would take a significant amount of work to be compatible with some add-ons and we are currently working on a complete UX/UI overhaul. Hopefully this sort of responsiveness will be addressed in this new release.
